from instaclient import InstaClient
from instaclient.errors import *

# Create a instaclient object. Place as driver_path argument the path that leads to where you saved the chromedriver.exe file
client = InstaClient(driver_path='chromedriver.exe')

try:
    client.login(username='therealmlkr@gmail.com', password='mareandistrugatorul')  # Go through Login Procedure
except VerificationCodeNecessary:
    # This error is raised if the user has 2FA turned on.
    code = input('Enter the 2FA security code generated by your Authenticator App or sent to you by SMS')
    client.input_verification_code(code)
except SuspisciousLoginAttemptError as error:
    # This error is reaised by Instagram
    if error.mode == SuspisciousLoginAttemptError.EMAIL:
        code = input('Enter the security code that was sent to you via email: ')
    else:
        code = input('Enter the security code that was sent to you via SMS: ')
    client.input_security_code(code)

# profile = client.get_profile('robert.palade')
# result = client.send_dm('madalinatugui', 'Sa ai o zi okey!')
max_followers_count = 10
target_user_followers = client.get_followers(user='robert.palade', count=max_followers_count)
followers_of_target_user = []
target_user_following = client.get_following(user='robert.palade', count=max_followers_count)
print(type(target_user_followers))
for follower in target_user_followers[0]:
    print("Target user follower: " + follower.username)
    followers_of_target_user.append(client.get_following(user=follower.username, count=max_followers_count))
print(f"First {max_followers_count} followers of the target user: " + str(followers_of_target_user))
print(f"First {max_followers_count} target user following: " + target_user_following)
count = 0
for one_following_target_user in target_user_following[0]:
    for one_following_not_target_user in followers_of_target_user:
        for one_following_not_palade_profile in one_following_not_target_user[0]:
            if one_following_target_user == one_following_not_palade_profile:
                print("Common following: " + one_following_target_user.username)

# profile.refresh() # syncing with instagram
